### ISSUE TITLE
unmatched characters

### ISSUE THREAD

**Issue by caseus-cattus** [matoruru/polybar-adapta-theme#2]
When i start bar, i get issues about unmatched characters like that
`warn: Dropping unmatched character  (U+f2db)`
https://imgur.com/a/NwKSM4h
I can see icons in terminal and in text editor when editing config, but it still throws warns and all of the bar features are not working.
https://imgur.com/a/1dO3nZG

**Comment by matoruru** [comment]
Thank you for giving me your issue! But I think this is the issue of polybar itself like [these](https://github.com/polybar/polybar/issues?q=is%3Aissue+unmatched+characters+is%3Aclosed).
